name: ehop_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.6  # Or the latest version

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_functions: ^5.4.0
  flutter_webrtc: ^0.13.1+hotfix.1
  permission_handler: ^12.0.0+1
  ionicons: ^0.2.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
    - assets/fonts/

  uses-material-design: true

